# -*- coding: utf-8 -*-
"""Tutorial_One.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QVsPxKoOuX5C0a7Pl4AlCou9K6rEPdU

## UFMFRR-15-M - Machine Vision

# Tutorial 1 - Python and Google Colab, Grouping
"""

import numpy as np  # import a package (numpy)
import cv2  #  opencv

#!pip list  # list all the packages that have been pre-installed

#!python --version  # show python version
print(cv2.__version__)  # show opencv version
print(np.__version__)  #show numpy version

"""# Test if a GPU is available"""

#!nvidia-smi

import tensorflow as tf
tf.test.gpu_device_name()

"""# Install a package/library"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install keras  # In fact, keras should have been pre-installed in Colab
from tensorflow import keras

"""# Basic data types

"""

x = 5  # int
y = 1.5  # float
z = True  # boolean
print(type(x))
print(type(y))
print(type(z))

machine = 'machine'
mv = machine + '_' + 'vision'  # concatenation of strings
print(mv)
print(type(mv))

"""* Please refer to some of the [useful string methods](https://docs.python.org/release/3.6.9/library/stdtypes.html#string-methods)

# Lists, Dictionaries, Sets and Tuples
"""

a = [1, 2, 3]
b = ['x', 'y', 'z']
a[1] = 'z'

print(a)
print(b)

"""* More on list [here](https://docs.python.org/release/3.6.9/tutorial/datastructures.html#more-on-lists)
* Read about [Dictionaries](https://docs.python.org/release/3.6.9/library/stdtypes.html#mapping-types-dict), [Sets](https://docs.python.org/release/3.6.9/library/stdtypes.html#set-types-set-frozenset) and [Tuples](https://docs.python.org/release/3.6.9/library/stdtypes.html?highlight=tuple#tuples) yourself

# Numpy

Create a numpy array
"""

a = np.arange(12)
a1 = np.arange(2, 20, 3)  # Return evenly spaced values within a given interval.
b = np.diag(a)  # Extract a diagonal or construct a diagonal array.
print(a)
print(a1)
print(b)

"""Reshape a numpy array"""

a = a.reshape(3,4)
print(a)
print('The shape of the array is: ' + str(a.shape))
print('The type of the elements: ' + a.dtype.name)

"""Add a number to all elements in an array"""

a = a + 5
print(a)

"""Slicing"""

c = a[0:2,2]
print(c)

"""* More on numpy [here](https://numpy.org/doc/1.18/reference/index.html)

## What you should do next

### 1. Teamup for the Coursework
Please follow the instructions of the tutors to form a group of 4 ~ 6 students for the coursework of the Machine Vision module. You can walk around and talk with each other during this grouping period. After agreeing with the other members of your group, you should register your name using the grouping link on the Blackboard system. Please note that you are only allowed to team up with the students in the same lab session.

### 2. Quiz
To self-check the learning performance, please finish the quiz on Mentimeter.

### 3. More practice in Python
Please download Week 1.doc on Blackboard and try to solve the questions in the worksheet.
"""